name: campus_connect
description: A campus life organization app for students

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.1.1
  timezone: ^0.9.2
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  table_calendar: ^3.0.9
  intl: ^0.18.0
  uuid: ^3.0.7
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/